# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackInviteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Emails requested')),
                ('timestamp', models.TimeField(auto_now_add=True, verbose_name='Time requested')),
            ],
        ),
    ]
